spring:
  datasource:
    druid:
      url: jdbc:mysql://43.138.170.129:3306/kafeidagede?serverTimezone=GMT%2B8
      username: kafeidagede
      password: FFZk7X4tZtLwfj6M
      connectionProperties: druid.stat.slowSqlMillis=5000;druid.stat.logSlowSql=true;





